[vfs-url]
AE-MT = https://visa.vfsglobal.com/are/en/mlt/login
AE-LUX = https://visa.vfsglobal.com/are/en/lux/login

AE-CHE = https://visa.vfsglobal.com/are/en/che/login
;AE-HUN = https://visa.vfsglobal.com/are/en/hun/login

